<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Josefina Sommer">
<meta name="author" content="Elnari Potgieter">
<meta name="author" content="David Simon">
<meta name="author" content="Ana Cristancho">
<meta name="author" content="Erik Paessler">

<title>KODAQS Academy | Course D2 Survey</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="results_mini_project_group_usa_files/libs/clipboard/clipboard.min.js"></script>
<script src="results_mini_project_group_usa_files/libs/quarto-html/quarto.js"></script>
<script src="results_mini_project_group_usa_files/libs/quarto-html/popper.min.js"></script>
<script src="results_mini_project_group_usa_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="results_mini_project_group_usa_files/libs/quarto-html/anchor.min.js"></script>
<link href="results_mini_project_group_usa_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="results_mini_project_group_usa_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="results_mini_project_group_usa_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="results_mini_project_group_usa_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="results_mini_project_group_usa_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction-all" id="toc-introduction-all" class="nav-link active" data-scroll-target="#introduction-all">Introduction (ALL)</a></li>
  <li><a href="#data-preparation-all" id="toc-data-preparation-all" class="nav-link" data-scroll-target="#data-preparation-all">Data Preparation (ALL)</a>
  <ul class="collapse">
  <li><a href="#load-packages-and-read-data" id="toc-load-packages-and-read-data" class="nav-link" data-scroll-target="#load-packages-and-read-data">Load Packages and Read Data</a></li>
  <li><a href="#compute-indices" id="toc-compute-indices" class="nav-link" data-scroll-target="#compute-indices">Compute Indices</a></li>
  </ul></li>
  <li><a href="#descriptive-analysis-all" id="toc-descriptive-analysis-all" class="nav-link" data-scroll-target="#descriptive-analysis-all">Descriptive Analysis (ALL)</a></li>
  <li><a href="#attention-checks-david" id="toc-attention-checks-david" class="nav-link" data-scroll-target="#attention-checks-david">Attention Checks (David)</a></li>
  <li><a href="#para-data-elnari-potgieter" id="toc-para-data-elnari-potgieter" class="nav-link" data-scroll-target="#para-data-elnari-potgieter">Para Data (Elnari Potgieter)</a></li>
  <li><a href="#missing-data-your-name" id="toc-missing-data-your-name" class="nav-link" data-scroll-target="#missing-data-your-name">Missing Data (YOUR NAME)</a></li>
  <li><a href="#response-distributions-your-name" id="toc-response-distributions-your-name" class="nav-link" data-scroll-target="#response-distributions-your-name">Response Distributions (YOUR NAME)</a></li>
  <li><a href="#response-styles-your-name" id="toc-response-styles-your-name" class="nav-link" data-scroll-target="#response-styles-your-name">Response Styles (YOUR NAME)</a></li>
  <li><a href="#all-together-all" id="toc-all-together-all" class="nav-link" data-scroll-target="#all-together-all">All together (ALL)</a></li>
  <li><a href="#discuss-all" id="toc-discuss-all" class="nav-link" data-scroll-target="#discuss-all">Discuss (ALL)</a></li>
  <li><a href="#references-all" id="toc-references-all" class="nav-link" data-scroll-target="#references-all">References (ALL)</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">KODAQS Academy | Course D2 Survey</h1>
<p class="subtitle lead"><em>Assignment Task Group USA</em></p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Josefina Sommer </p>
             <p>Elnari Potgieter </p>
             <p>David Simon </p>
             <p>Ana Cristancho </p>
             <p>Erik Paessler </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">08.04.2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">08.04.2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="introduction-all" class="level2">
<h2 class="anchored" data-anchor-id="introduction-all">Introduction (ALL)</h2>
<p><em>Science-related populism</em> has been conceptualized as a set of ideas suggesting a fundamental conflict between an allegedly virtuous people and an allegedly immoral academic elite over who should be in charge of science-related decision-making and over what is deemed true knowledge” <span class="citation" data-cites="mede2020">(<a href="#ref-mede2020" role="doc-biblioref">Mede et al., 2020</a>)</span>.</p>
<p>Conceptually, science-related populism consists of four major components:</p>
<ul>
<li>the ordinary people,</li>
<li>the academic elite,</li>
<li>science-related decision-making sovereignty, and</li>
<li>truth-speaking sovereignty.</li>
</ul>
<p>This is the final assignment task of KODAQS Academy, Course D2 Survey of “Team USA” <br></p>
<p>It contains sections for several kinds of data quality indicators in regards to the construct above.</p>
<p>Some parts of the assignment were intended to be completed collaboratively and others individually, each teammate was responsible for at least one section of the indicator. Overall, we worked together constructively and collaboratively on this script. Consequently, the listed names do not fully capture the collaborative nature of the work, as all team members contributed across multiple sections.</p>
</section>
<section id="data-preparation-all" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation-all">Data Preparation (ALL)</h2>
<p>In a first step you have to define your R setup (e.g., install und load relevant packages) and need to read in the dataset. Do your basic cleanup and wrangling here (e.g.&nbsp;filtering for your country group, selection of used variables etc.).</p>
<section id="load-packages-and-read-data" class="level3">
<h3 class="anchored" data-anchor-id="load-packages-and-read-data">Load Packages and Read Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">####  ------------- Load Packages ------------- ####</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)           <span class="co"># find files</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)      <span class="co"># data management</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)          <span class="co"># descriptives</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(labelled)       <span class="co"># data labels</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="do">####  ------------- Read Data ------------- ####</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># data_raw</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>data_raw <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"00_data/ds_full.csv"</span>), <span class="at">sep =</span> <span class="st">";"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(COUNTRY_CODE <span class="sc">==</span> <span class="st">"USA"</span>)  <span class="sc">%&gt;%</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">na_if</span>(., <span class="dv">99</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.character), <span class="sc">~</span> <span class="fu">na_if</span>(., <span class="st">"99"</span>)))</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># raw data needs to be processed (a liitle bit)</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Source: https://osf.io/5c3qd/files/xz8bw</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co"># (1.) Identify and exclude duplicate completes</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize ID data (stored in separate csv file)</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>ds_id <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"00_data/ds_id.csv"</span>), <span class="at">sep =</span> <span class="st">";"</span>) </span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>data_raw_tmp <span class="ot">&lt;-</span> <span class="fu">left_join</span>(data_raw, ds_id, <span class="at">by =</span> <span class="st">"ID_QUALTRICS"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ID_POLLCMPNY) <span class="sc">%&gt;%</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(ID_POLLCMPNY) <span class="sc">|</span> <span class="fu">row_number</span>(Recorded) <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Confirm that there are no duplicate completes (empty tibble)</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>data_raw_tmp <span class="sc">%&gt;%</span> </span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(ID_POLLCMPNY)) <span class="sc">%&gt;%</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ID_POLLCMPNY) <span class="sc">%&gt;%</span> </span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 2
# ℹ 2 variables: ID_POLLCMPNY &lt;chr&gt;, n &lt;int&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># % removed</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>per_rem1 <span class="ot">&lt;-</span> ((<span class="fu">nrow</span>(data_raw) <span class="sc">-</span> <span class="fu">nrow</span>(data_raw_tmp)) <span class="sc">/</span> <span class="fu">nrow</span>(data_raw)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>data_raw <span class="ot">&lt;-</span> data_raw_tmp</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(ds_id)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(data_raw_tmp)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># (2.) Exclude outlier values for age</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co"># % outliers</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>per_out <span class="ot">&lt;-</span> <span class="fu">mean</span>(data_raw<span class="sc">$</span>DEM_AGE <span class="sc">&lt;</span> <span class="dv">18</span> <span class="sc">|</span> data_raw<span class="sc">$</span>DEM_AGE <span class="sc">&gt;</span> <span class="dv">100</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Set to NA</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>data_raw <span class="ot">&lt;-</span> data_raw <span class="sc">%&gt;%</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">DEM_AGE =</span> <span class="fu">if_else</span>(DEM_AGE <span class="sc">&lt;</span> <span class="dv">18</span> <span class="sc">|</span> DEM_AGE <span class="sc">&gt;</span> <span class="dv">100</span>, </span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">as.numeric</span>(<span class="cn">NA</span>),</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>                      DEM_AGE)         </span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="co"># (3.) Gender (1 = male)</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>data_raw <span class="ot">&lt;-</span> data_raw  <span class="sc">%&gt;%</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DEM_GENDER =</span> <span class="fu">ifelse</span>(DEM_GENDER <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DEM_GENDER =</span> <span class="fu">as.factor</span>(DEM_GENDER))</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="co"># (4.) Exclude respondents who did not reach the first question = DEM_GENDER</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>data_raw_tmp <span class="ot">&lt;-</span> data_raw <span class="sc">%&gt;%</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(DEM_GENDER))</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="co"># % removed</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>per_rem2 <span class="ot">&lt;-</span> ((<span class="fu">nrow</span>(data_raw) <span class="sc">-</span> <span class="fu">nrow</span>(data_raw_tmp)) <span class="sc">/</span> <span class="fu">nrow</span>(data_raw)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>data_raw <span class="ot">&lt;-</span> data_raw_tmp</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(data_raw_tmp)</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a><span class="co"># data</span></span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"00_data/ds_final.csv"</span>), <span class="at">sep =</span> <span class="st">";"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(COUNTRY_CODE <span class="sc">==</span> <span class="st">"USA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The following packages are used in this script:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">installed.packages</span>()[<span class="fu">names</span>(<span class="fu">sessionInfo</span>()<span class="sc">$</span>otherPkgs), <span class="st">"Version"</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    psych  labelled     skimr lubridate   forcats   stringr     dplyr     purrr 
  "2.5.6"  "2.16.0"   "2.2.2"   "1.9.3"   "1.0.1"   "1.6.0"   "1.1.4"   "1.0.2" 
    readr     tidyr    tibble   ggplot2 tidyverse      here 
  "2.1.6"   "1.3.2"   "3.3.1"   "4.0.1"   "2.0.0"   "1.0.1" </code></pre>
</div>
</div>
<p>Two datasets are read:</p>
<ul>
<li><code>data_raw</code>: The raw dataset before any cleaning or transformations.</li>
<li><code>data</code>: The analysis-ready dataset, including post-stratification.</li>
</ul>
<p>Not all calculations can be performed using the pre-processed data, as some information is already missing. Therefore, the raw data were processed as follows:</p>
<ol type="1">
<li>Duplicate respondents were excluded: 0.32%</li>
<li>Age values outside the range of 18 to 100 were set to NA: 0.02%</li>
<li>Gender was recoded into a binary variable (1 = male), with self-described responses excluded from this coding.</li>
<li>Only particpiants were included who reached the beginning of the actualy questionaire (= question 1: DEM_GENDER): 6.13%</li>
</ol>
<p>Since the analysis-ready dataset <code>data</code> was too limited, we performed all calculations on the dataset <code>data_raw</code>.</p>
</section>
<section id="compute-indices" class="level3">
<h3 class="anchored" data-anchor-id="compute-indices">Compute Indices</h3>
<p><em>Science-related populist attitudes</em> were measuered with 8 items on 4 dimensions on a 5-point scale each (1 = strongly disagree to 5 = strongly agree <span class="citation" data-cites="mede2020">(<a href="#ref-mede2020" role="doc-biblioref">Mede et al., 2020</a>)</span>, aggregated with the Goertz approach <span class="citation" data-cites="wuttke2020">(<a href="#ref-wuttke2020" role="doc-biblioref">Wuttke et al., 2020</a>)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">####  ------------ Compute Indices ------------ ####</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># SCIPOP_goertz: Science-related populist attitudes</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute overall and dimension scores</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>data_raw <span class="ot">&lt;-</span> data_raw <span class="sc">%&gt;%</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">SCIPOP_PPL_m =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">c</span>(SCIPOP_common, SCIPOP_good)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">SCIPOP_ELI_m =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">c</span>(SCIPOP_advantage, SCIPOP_cahoots)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">SCIPOP_DEC_m =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">c</span>(SCIPOP_influence, SCIPOP_involved)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">SCIPOP_TRU_m =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">c</span>(SCIPOP_lifeexp, SCIPOP_rely)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">SCIPOP_goertz =</span> <span class="fu">pmin</span>(SCIPOP_PPL_m, SCIPOP_ELI_m, SCIPOP_DEC_m, SCIPOP_TRU_m, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>data_raw <span class="ot">&lt;-</span> labelled<span class="sc">::</span><span class="fu">set_variable_labels</span>(</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  data_raw,</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">SCIPOP_goertz =</span> <span class="st">"Science-related populist attitudes: overall (Goertz score)"</span>,</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">SCIPOP_PPL_m =</span> <span class="st">"Science-related populist attitudes: conceptions of the ordinary people (mean)"</span>,</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">SCIPOP_ELI_m =</span> <span class="st">"Science-related populist attitudes: conceptions of the academic elite (mean)"</span>,</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">SCIPOP_DEC_m =</span> <span class="st">"Science-related populist attitudes: demands for decision-making sovereignty (mean)"</span>,</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">SCIPOP_TRU_m =</span> <span class="st">"Science-related populist attitudes: demands for truth-speaking sovereignty (mean)"</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="descriptive-analysis-all" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-analysis-all">Descriptive Analysis (ALL)</h2>
<p>Provide basic descriptive statistics for your (sub)sample and instrument(s).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>data_des <span class="ot">&lt;-</span> data_raw  <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(DEM_AGE, DEM_GENDER, <span class="co"># demographics</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>         SCIPOP_common, SCIPOP_good, SCIPOP_advantage, SCIPOP_cahoots, SCIPOP_influence, SCIPOP_involved, SCIPOP_lifeexp, SCIPOP_rely,<span class="co"># items</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>         SCIPOP_PPL_m, SCIPOP_ELI_m, SCIPOP_DEC_m, SCIPOP_TRU_m, SCIPOP_goertz) <span class="sc">%&gt;%</span> <span class="co"># scales</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>data_des</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">Piped data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">4362</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">15</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">factor</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">14</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">ordered</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: left;">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">DEM_GENDER</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">0: 2409, 1: 1953</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 3%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">DEM_AGE</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">44.73</td>
<td style="text-align: right;">16.87</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">31.0</td>
<td style="text-align: right;">42.0</td>
<td style="text-align: right;">58.0</td>
<td style="text-align: right;">100</td>
<td style="text-align: left;">▇▇▆▃▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">SCIPOP_common</td>
<td style="text-align: right;">781</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">3.69</td>
<td style="text-align: right;">1.06</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▁▂▇▇▆</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SCIPOP_good</td>
<td style="text-align: right;">779</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">3.61</td>
<td style="text-align: right;">1.07</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▁▂▇▇▆</td>
</tr>
<tr class="even">
<td style="text-align: left;">SCIPOP_advantage</td>
<td style="text-align: right;">779</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">3.22</td>
<td style="text-align: right;">1.30</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▃▅▇▆▆</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SCIPOP_cahoots</td>
<td style="text-align: right;">777</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">3.32</td>
<td style="text-align: right;">1.31</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▃▅▇▆▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">SCIPOP_influence</td>
<td style="text-align: right;">779</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">3.45</td>
<td style="text-align: right;">1.18</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▂▃▇▆▆</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SCIPOP_involved</td>
<td style="text-align: right;">778</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">3.54</td>
<td style="text-align: right;">1.16</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▂▂▇▇▆</td>
</tr>
<tr class="even">
<td style="text-align: left;">SCIPOP_lifeexp</td>
<td style="text-align: right;">780</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">3.39</td>
<td style="text-align: right;">1.21</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▂▃▇▆▆</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SCIPOP_rely</td>
<td style="text-align: right;">780</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">3.32</td>
<td style="text-align: right;">1.28</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▃▃▇▆▆</td>
</tr>
<tr class="even">
<td style="text-align: left;">SCIPOP_PPL_m</td>
<td style="text-align: right;">778</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">3.65</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">4.5</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▁▂▅▇▆</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SCIPOP_ELI_m</td>
<td style="text-align: right;">776</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">3.27</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▃▆▆▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">SCIPOP_DEC_m</td>
<td style="text-align: right;">777</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">3.50</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">4.5</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▂▃▆▇▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SCIPOP_TRU_m</td>
<td style="text-align: right;">777</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">3.36</td>
<td style="text-align: right;">1.13</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▃▅▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">SCIPOP_goertz</td>
<td style="text-align: right;">776</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">2.84</td>
<td style="text-align: right;">1.15</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▆▇▇▆▃</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="attention-checks-david" class="level2">
<h2 class="anchored" data-anchor-id="attention-checks-david">Attention Checks (David)</h2>
<p>The first kind of data quality indicators are check items. What check items are provided in the dataset and did participants pass the check?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>attcheck1.fails <span class="ot">&lt;-</span> <span class="cf">function</span>(attcheck1){</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  n_valid <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(attcheck1), <span class="at">na.rm =</span> T)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  n_fails <span class="ot">&lt;-</span> <span class="fu">sum</span>(attcheck1 <span class="sc">!=</span> <span class="st">"213"</span>, <span class="at">na.rm =</span> T)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>((<span class="dv">1</span> <span class="sc">-</span> ((n_valid <span class="sc">-</span> n_fails) <span class="sc">/</span> n_valid)) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>attcheck2.fails <span class="ot">&lt;-</span> <span class="cf">function</span>(attcheck2){</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  n_valid <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(attcheck2), <span class="at">na.rm =</span> T)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  n_fails <span class="ot">&lt;-</span> <span class="fu">sum</span>(attcheck2 <span class="sc">%in%</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>, <span class="at">na.rm =</span> T) <span class="sc">+</span> <span class="fu">sum</span>(attcheck2 <span class="sc">==</span> <span class="sc">-</span><span class="dv">99</span>, <span class="at">na.rm =</span> T)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>((<span class="dv">1</span> <span class="sc">-</span> ((n_valid <span class="sc">-</span> n_fails) <span class="sc">/</span> n_valid)) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Using the provided code by Mede <span class="citation" data-cites="mede2020">(<a href="#ref-mede2020" role="doc-biblioref">2020</a>)</span>, the first attention of writing “213” into a text box was failed by 4% of participants and</p>
<p>27% of participants who reached the second attention check of selecting “strongly disagree” for an extra item in a scale of science-related populist attitudes did not pass it.</p>
<p>So, the data set is partially filtered by design: Participants who failed the first attention check were redirected to the end of the survey and did not participate further. Consequently, they are not included among those who answered the Attitudes-Scale.</p>
<p>The second attention check was part of the Attitudes-Scale and is therefore particularly interesting for this assignment. Participants who failed the second attention check were also redirected to the end of the survey. The attention check was the last item on the scale.</p>
<p>Several participants answered the questions incorrectly and were flagged as having failed by the authors. One could argue about whether these were truly careless respondents. This is particularly questionable for those who wrote the correct number in words instead of as a number, e.g., “two hundred thirteen.”, one person used a lowercase L instead of 1. Others are more likely to be careless, e.g.&nbsp;“Very nice to have a good time at your new office and I love love you bye bye good mama bye mama good night too love love you”. Others stay unclear or “missing”, e.g.&nbsp;“i don’t know”. The following table provides an overview about the frequency:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>attentioncheck_clean <span class="ot">&lt;-</span> data_raw<span class="sc">$</span>ATTCHECK_NUMBER <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_to_lower</span>() <span class="sc">%&gt;%</span>                       <span class="co"># all lowercase</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_trim</span>() <span class="sc">%&gt;%</span>                           <span class="co"># remove spaces</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_replace_all</span>(<span class="st">"’"</span>, <span class="st">"'"</span>) <span class="sc">%&gt;%</span>            <span class="co"># remove apostrophes</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_replace_all</span>(<span class="st">"[[:punct:]]"</span>, <span class="st">" "</span>) <span class="sc">%&gt;%</span>  <span class="co"># remove punctuation characters</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_squish</span>()                             <span class="co"># remove extra spaces</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>attentioncheck_table <span class="ot">&lt;-</span> <span class="fu">case_when</span>(</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># numeric variants</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_detect</span>(attentioncheck_clean, <span class="st">"</span><span class="sc">\\</span><span class="st">b213</span><span class="sc">\\</span><span class="st">b|</span><span class="sc">\\</span><span class="st">b2l3</span><span class="sc">\\</span><span class="st">b"</span>) </span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> <span class="st">"Correct"</span>,</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># numeric split with extra spaces / periods / commas</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_detect</span>(attentioncheck_clean, <span class="st">"^2</span><span class="sc">\\</span><span class="st">s*1</span><span class="sc">\\</span><span class="st">s*3$"</span>) </span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> <span class="st">"Correct"</span>,</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># word variants</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_detect</span>(attentioncheck_clean,</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>             <span class="st">"two.*hund.*thirt|two.*thirt|two.*one.*three|twoh.*thirt|twothirt|twoonethree|doscientos trece"</span>) </span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> <span class="st">"Correct: written in words"</span>,</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># missing</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>  attentioncheck_clean <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">""</span>, <span class="st">"none"</span>, <span class="st">"-99"</span>, <span class="st">"i don't know"</span>) <span class="sc">|</span></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">str_detect</span>(attentioncheck_clean, <span class="st">"[0-9]"</span>) <span class="sc">&amp;</span> </span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">str_detect</span>(attentioncheck_clean, <span class="st">"two|doscientos"</span>) <span class="sc">~</span> <span class="st">"Missing"</span>,</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>  <span class="co"># incorrect</span></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Incorrect"</span></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(attentioncheck_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>attentioncheck_table
                  Correct Correct: written in words                 Incorrect 
                     3753                        77                       518 
                  Missing 
                       14 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>prop <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(attentioncheck_table))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The number of failures on the second attention check decreases from 27% to 12%.</p>
<p>These are candidates of carless respondents and therefore “flagged” in this section.</p>
</section>
<section id="para-data-elnari-potgieter" class="level2">
<h2 class="anchored" data-anchor-id="para-data-elnari-potgieter">Para Data (Elnari Potgieter)</h2>
<p>This section looks at the response time indices of the USA data set, considering total response time, average time per item, relative completion time and speeding factor. This is a draft version.</p>
<ol type="1">
<li>Total Response Time</li>
</ol>
<p>Total response time refers to the time it takes a respondent to complete the survey. The data set contains a “Duration” variable, analysed here, capturing response time in seconds.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Key Descriptives of Duration variable (in seconds)</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span> (data_raw<span class="sc">$</span>Duration)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   vars    n    mean      sd median trimmed    mad min    max  range  skew
X1    1 4361 1090.11 4898.51    620  692.78 563.39  10 213592 213582 29.51
   kurtosis    se
X1  1082.39 74.18</code></pre>
</div>
</div>
<p>Mean (1174.57) larger than median (905), showing right / positive skew in data. Further analysis to look out for high value outliers. Minimum at 133 seconds (2.22 minutes), and maximum at 26943 seconds (about 7 and a half hours).</p>
<p>The results do not appear to show any missing / incorrectly coded data, so no need for further data cleaning. Further consideration to percentiles / quartiles.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Consider quartiles</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(data_raw<span class="sc">$</span>Duration)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">data_raw$Duration</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">4362</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">data</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1090.11</td>
<td style="text-align: right;">4898.51</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">283</td>
<td style="text-align: right;">620</td>
<td style="text-align: right;">1101</td>
<td style="text-align: right;">213592</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Minimum (133) lower p25 (591), maximum (26953) much higher than mean (1174.57) and p75 (1341.25). The extreme high outliers may be due to opening the survey and only answering the survey later. This does not necessarily mean they were not paying attention when they were answering, so I don’t think their answers are necessarily invalid. However, on the lower end, 2.22 minutes for a survey with 111 items (Mede et al., 2025) - some of which open ended - sounds very short.</p>
<p>Box plots (in seconds) for further investigation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot using base R</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(data_raw<span class="sc">$</span>Duration,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Boxplot of Durations"</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Duration (seconds)"</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">border =</span> <span class="st">"darkblue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="results_mini_project_group_usa_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="2" type="1">
<li>Average Time per Item</li>
</ol>
<p>The average time per item indicator captures the average (mean) time spent on survey questions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of items</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>num_items <span class="ot">&lt;-</span> <span class="dv">111</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the average time per item for each respondent</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>average_time_per_item <span class="ot">&lt;-</span> data_raw<span class="sc">$</span>Duration <span class="sc">/</span> num_items</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the mean of all average times per item</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>mean_average_time_per_item <span class="ot">&lt;-</span> <span class="fu">mean</span>(average_time_per_item)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Output the results</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Average time per item for each respondent (in seconds):</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Average time per item for each respondent (in seconds):</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Mean of all average times per item (in seconds):"</span>, mean_average_time_per_item, <span class="st">"seconds</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mean of all average times per item (in seconds): NA seconds</code></pre>
</div>
</div>
<p>The average time per item is 10.58 seconds. However, the extreme high outliers may impact this result.</p>
<p>We proceed by looking at the number and proportion of respondents with an average time per item below 2 seconds (as per the course example) - this cut off can be changed for the final version.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify respondents who fall below the cutoff of 2 seconds (as per example in course)</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>below_cutoff <span class="ot">&lt;-</span> <span class="fu">which</span>(average_time_per_item <span class="sc">&lt;</span> cutoff)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Count of respondents below the cutoff</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>count_below_cutoff <span class="ot">&lt;-</span> <span class="fu">length</span>(below_cutoff)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Proportion of respondents below the cutoff</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>proportion_below_cutoff <span class="ot">&lt;-</span> count_below_cutoff <span class="sc">/</span> <span class="fu">length</span>(data_raw<span class="sc">$</span>Duration)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Respondents below the cutoff of"</span>, cutoff, <span class="st">"seconds:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Respondents below the cutoff of 2 seconds:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(below_cutoff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]    1    2    3    4   49   50   72   75   76   77   80   82   83   86  113
 [16]  114  115  116  119  120  121  125  128  131  132  141  149  151  152  156
 [31]  158  162  166  187  194  197  199  202  207  219  224  230  236  240  246
 [46]  248  264  270  277  284  294  307  333  334  335  336  337  338  339  341
 [61]  348  354  366  384  387  388  390  401  402  408  410  411  420  422  426
 [76]  428  430  431  438  469  470  472  473  476  477  479  481  487  505  507
 [91]  516  527  528  536  537  542  547  561  571  575  577  586  587  589  591
[106]  612  613  614  615  616  617  622  623  624  652  655  662  669  673  677
[121]  678  683  685  687  689  709  710  720  723  728  730  732  733  735  738
[136]  740  744  745  752  756  760  774  775  776  778  784  787  796  797  798
[151]  799  816  818  827  834  837  839  840  842  844  845  846  847  848  849
[166]  850  851  852  853  854  855  856  857  858  859  860  861  862  864  865
[181]  867  875  881  882  883  884  885  888  889  890  891  892  893  894  895
[196]  896  898  900  902  903  904  906  909  911  917  920  921  922  923  926
[211]  933 1009 1011 1012 1013 1044 1045 1047 1048 1049 1101 1122 1126 1130 1134
[226] 1148 1193 1194 1195 1198 1199 1203 1209 1214 1216 1224 1234 1251 1254 1256
[241] 1264 1405 1428 1433 1434 1450 1466 1467 1476 1477 1484 1489 1492 1525 1535
[256] 1537 1539 1542 1548 1550 1565 1566 1573 1584 1592 1607 1609 1614 1630 1640
[271] 1658 1661 1668 1674 1708 1714 1715 1718 1719 1720 1722 1723 1726 1738 1766
[286] 1768 1769 1770 1773 1775 1779 1793 1796 1797 1798 1807 1811 1827 1836 1868
[301] 1905 1906 1913 1918 1979 1984 1994 1999 2000 2006 2013 2029 2030 2036 2037
[316] 2038 2042 2043 2044 2045 2050 2052 2059 2063 2064 2065 2076 2115 2116 2117
[331] 2118 2119 2120 2121 2122 2123 2124 2125 2126 2127 2128 2129 2130 2131 2132
[346] 2133 2134 2135 2136 2137 2138 2139 2140 2141 2142 2143 2145 2146 2147 2148
[361] 2149 2150 2151 2158 2192 2193 2194 2195 2196 2197 2198 2199 2200 2201 2202
[376] 2203 2207 2209 2211 2212 2214 2219 2220 2221 2226 2227 2228 2229 2241 2242
[391] 2244 2246 2247 2248 2249 2253 2255 2256 2257 2259 2260 2262 2264 2267 2273
[406] 2276 2280 2281 2282 2285 2287 2289 2291 2292 2293 2296 2299 2300 2307 2320
[421] 2321 2327 2328 2331 2332 2336 2337 2338 2341 2342 2343 2344 2348 2349 2350
[436] 2355 2357 2358 2360 2362 2364 2365 2367 2368 2370 2374 2376 2378 2382 2383
[451] 2385 2387 2392 2397 2398 2399 2400 2401 2402 2403 2404 2410 2411 2412 2416
[466] 2417 2419 2421 2422 2424 2425 2428 2429 2431 2432 2437 2439 2441 2443 2445
[481] 2446 2448 2449 2450 2451 2452 2455 2457 2462 2464 2465 2466 2468 2469 2471
[496] 2472 2476 2478 2481 2489 2496 2499 2502 2504 2505 2506 2511 2513 2515 2516
[511] 2519 2520 2521 2522 2523 2525 2528 2534 2536 2545 2551 2552 2553 2556 2557
[526] 2560 2564 2565 2566 2567 2572 2573 2576 2578 2582 2585 2587 2607 2610 2613
[541] 2615 2616 2622 2630 2631 2632 2633 2634 2635 2636 2637 2639 2641 2643 2645
[556] 2647 2649 2651 2653 2656 2657 2661 2664 2667 2669 2693 2694 2695 2712 2730
[571] 2734 2735 2740 2743 2745 2746 2748 2754 2757 2762 2763 2764 2765 2768 2772
[586] 2775 2776 2784 2786 2790 2793 2798 2803 2806 2811 2819 2823 2828 2833 2834
[601] 2837 2841 2853 2855 2860 2886 2887 2891 2906 2926 2930 2940 2941 2951 2953
[616] 2991 3010 3061 3062 3063 3065 3067 3068 3071 3074 3083 3087 3089 3092 3095
[631] 3098 3102 3104 3105 3106 3111 3112 3113 3116 3119 3121 3122 3124 3125 3126
[646] 3128 3131 3132 3135 3136 3137 3140 3141 3145 3148 3149 3150 3152 3154 3155
[661] 3157 3159 3161 3166 3175 3179 3180 3184 3190 3203 3213 3214 3216 3223 3239
[676] 3240 3243 3251 3254 3274 3291 3294 3319 3325 3331 3339 3349 3376 3412 3413
[691] 3415 3418 3423 3431 3445 3449 3456 3459 3481 3492 3499 3500 3511 3537 3539
[706] 3577 3578 3579 3580 3581 3582 3585 3586 3592 3599 3668 3713 3765 3766 3771
[721] 3772 3774 3804 3809 3830 3850 3859 3863 3894 3896 3897 3900 3901 3902 3909
[736] 3919 3962 3965 3970 3971 3973 3979 3991 4003 4029 4031 4038 4042 4043 4045
[751] 4047 4048 4049 4053 4078 4082 4087 4095 4098 4100 4104 4112 4113 4114 4116
[766] 4118 4119 4120 4121 4122 4123 4124 4126 4128 4129 4130 4134 4135 4136 4138
[781] 4141 4143 4146 4147 4150 4151 4152 4153 4154 4155 4156 4157 4158 4159 4160
[796] 4161 4162 4163 4164 4166 4169 4170 4171 4173 4174 4175 4176 4177 4178 4179
[811] 4181 4185 4186 4189 4194 4197 4198 4200 4202 4203 4204 4206 4207 4210 4211
[826] 4215 4216 4217 4222 4229 4239 4245 4258 4263 4275 4288 4297 4318 4335 4337
[841] 4339 4346 4353 4357 4361</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Count of respondents below the cutoff:"</span>, count_below_cutoff, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Count of respondents below the cutoff: 845 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Proportion of respondents below the cutoff:"</span>, proportion_below_cutoff, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Proportion of respondents below the cutoff: 0.1937185 </code></pre>
</div>
</div>
<p>Only 12 respondents (0.005%) had an average time per item below 2 seconds.</p>
<p>Further steps: Decide whether to run the average time analysis without high-end outliers, and then identify those with significantly slower average times per item. Decide whether the cut off should be MRT - 4.4 seconds - per item (Andreadis, 2021)</p>
<ol start="3" type="1">
<li>Relative Time Completion</li>
</ol>
<p>Relative time completion compares the speed of completing the questionnaire for a respondent to the median completion time of the sample.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Median completion time of the sample</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>median_time <span class="ot">&lt;-</span> <span class="dv">905</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the relative completion time for each respondent</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>relative_completion_time <span class="ot">&lt;-</span> data_raw<span class="sc">$</span>Duration<span class="sc">/</span> median_time</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Output the results</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Relative completion time for each respondent:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Relative completion time for each respondent:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics for relative completion times</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Summary of relative completion times:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Summary of relative completion times:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(relative_completion_time))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.      NA's 
  0.01105   0.31271   0.68508   1.20454   1.21657 236.01326         1 </code></pre>
</div>
</div>
<p>As per the course example, we calculate how many respondents are faster than twice the median completion time. Please note my findings here need to be revised. I need to check if that is median response time or median of the relative completion time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify respondents who are faster than two times the median completion time</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>faster_than_cutoff <span class="ot">&lt;-</span> <span class="fu">which</span>(relative_completion_time <span class="sc">&gt;</span> cutoff)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Count of respondents faster than two times the median completion time</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>count_faster <span class="ot">&lt;-</span> <span class="fu">length</span>(faster_than_cutoff)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Proportion of respondents faster than two times the median completion time</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>proportion_faster <span class="ot">&lt;-</span> count_faster <span class="sc">/</span> <span class="fu">length</span>(data_raw<span class="sc">$</span>Duration)</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify rows where respondents are twice as fast as the median response time</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>twice_faster_rows <span class="ot">&lt;-</span> <span class="fu">which</span>(relative_completion_time <span class="sc">&lt;</span> <span class="dv">2</span>)</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Output the results</span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Respondents faster than two times the median completion time:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Respondents faster than two times the median completion time:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Count of respondents faster than two times the median:"</span>, count_faster, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Count of respondents faster than two times the median: 408 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Proportion of respondents faster than two times the median:"</span>, proportion_faster, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Proportion of respondents faster than two times the median: 0.09353508 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Rows where respondents are twice as fast as the median response time:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Rows where respondents are twice as fast as the median response time:</code></pre>
</div>
</div>
<p>317 (13%) respondents where twice as fast as the median of the relative completion time. I did not print the rows for now, as they are quite many.</p>
<ol start="4" type="1">
<li>Speeding Factor</li>
</ol>
<p>Leiner, 2019 suggests a factor of larger than two as outliers.This is calculated using their response time in relation to the median of the sample.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Speeding factor</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the speeding factor for each respondent</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>speeding_factor <span class="ot">&lt;-</span> median_time <span class="sc">/</span> data_raw<span class="sc">$</span>Duration</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Output the results</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Speeding factor for each respondent:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Speeding factor for each respondent:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics for speeding factors</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Summary of speeding factors:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Summary of speeding factors:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(speeding_factor))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's 
 0.00424  0.82198  1.45968  5.28521  3.19788 90.50000        1 </code></pre>
</div>
</div>
<p>Some outliers with a speeding factor above 2, when considering maximum (6.8).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify outliers (speeding factor &gt; 2)</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>outliers <span class="ot">&lt;-</span> <span class="fu">which</span>(speeding_factor <span class="sc">&gt;</span> <span class="dv">2</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Count of outliers</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>outlier_count <span class="ot">&lt;-</span> <span class="fu">length</span>(outliers)</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Proportion of outliers</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>outlier_proportion <span class="ot">&lt;-</span> outlier_count <span class="sc">/</span> <span class="fu">length</span>(data<span class="sc">$</span>Duration)</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Output the count and proportion of outliers</span></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Count of outliers (speeding factor &gt; 2):"</span>, outlier_count, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Count of outliers (speeding factor &gt; 2): 1681 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Proportion of outliers:"</span>, outlier_proportion, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Proportion of outliers: 0.6568972 </code></pre>
</div>
</div>
<p>348 (14%) respondents with speeding factor above 2. I did not print the rows for now, as there are quite many.</p>
<ol start="5" type="1">
<li>Summary</li>
</ol>
<p>Suggestion to compare the rows highlighted throgugh this analysis with the rows identified in other analysed (for example attention checks) to identify respondents which may need to be flagged.</p>
<ol start="6" type="1">
<li>References</li>
</ol>
<p>Knopf T., &amp; Roth M. (2025). Tools and Workflows for Survey Data – Paradata [Slide deck]. In F. Bemmann, J. Blumenberg, J. Daikeler, F. Draxler, M. Fritz, F. Keusch, F. Krämer, S. Jünger, S. Kapidzic, T. Knopf, F. Kreuter, V. Kunz, L. Mejia Lopez, Y. Peters, B. Rammstedt, P. Siegers, J. Sun, C. Wagner, K. Weller, C. E. Yildiz, &amp; L. Young (Eds.), KODAQS Academy.</p>
<p>Leiner, Dominik J.. “Too Fast, too Straight, too Weird: Non-Reactive Indicators for Meaningless Data in Internet Surveys.” Survey research methods 13 (2019): 229-248.</p>
<p>Mede, N.G., Cologna, V., Berger, S. et al.&nbsp;Perceptions of science, science communication, and climate change attitudes in 68 countries – the TISP dataset. Sci Data 12, 114 (2025). https://doi.org/10.1038/s41597-024-04100-7</p>
</section>
<section id="missing-data-your-name" class="level2">
<h2 class="anchored" data-anchor-id="missing-data-your-name">Missing Data (YOUR NAME)</h2>
<p>The third kind of data quality indicators are missing data. How much data is missing, which data missing pattern occurs and are there cases with many missing data? (in respect to your choosen instrument(s) / variable(s)).</p>
</section>
<section id="response-distributions-your-name" class="level2">
<h2 class="anchored" data-anchor-id="response-distributions-your-name">Response Distributions (YOUR NAME)</h2>
<p>The fourth kind of data quality indicators are response distributions. Which indicators do you deem relevant and which criterion do you use for flagging?</p>
</section>
<section id="response-styles-your-name" class="level2">
<h2 class="anchored" data-anchor-id="response-styles-your-name">Response Styles (YOUR NAME)</h2>
<p>The last kind of data quality indicators are response styles. Which style(s) do you want to focus on and how do you flag concerning cases?</p>
</section>
<section id="all-together-all" class="level2">
<h2 class="anchored" data-anchor-id="all-together-all">All together (ALL)</h2>
<p>Now that you have different flags you may want to combine them. Which combinations do you deem suitable? And how to (partly) filter the identified cases?</p>
</section>
<section id="discuss-all" class="level2">
<h2 class="anchored" data-anchor-id="discuss-all">Discuss (ALL)</h2>
<p>Discuss central findings shortly! Make some statements on your final decision in respect to include/exclude rules (cutoffs/thresholds/filter combination), data loss, consequences for planned analyses, and any notable what you like to adress.</p>
</section>
<section id="references-all" class="level2">
<h2 class="anchored" data-anchor-id="references-all">References (ALL)</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-mede2020" class="csl-entry" role="listitem">
Mede, N. G., Schäfer, M. S., &amp; Füchslin, T. (2020). The SciPop scale for measuring science-related populist attitudes in surveys: Development, test, and validation. <em>International Journal of Public Opinion Research</em>, <em>33</em>(2), 273–293. <a href="https://doi.org/10.1093/ijpor/edaa026">https://doi.org/10.1093/ijpor/edaa026</a>
</div>
<div id="ref-wuttke2020" class="csl-entry" role="listitem">
Wuttke, A., SCHIMPF, C., &amp; Schoen, H. (2020). When the whole is greater than the sum of its parts: On the conceptualization and measurement of populist attitudes and other multidimensional constructs. <em>American Political Science Review</em>, <em>114</em>, 1–19. <a href="https://doi.org/10.1017/S0003055419000807">https://doi.org/10.1017/S0003055419000807</a>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Pay Attention Please!
</div>
</div>
<div class="callout-body-container callout-body">
<p>For final submission upload your prepared Quarto document and an exported html-file into Moodle, week 8, section “Final Assignment Course D2 Survey LU8.1”. <strong>FINAL DEADLINE will be June 20th, 2025, sharp!</strong></p>
</div>
</div>
<p><span style="color:#1E8CC8;"><strong>Good luck and see you next Thursday (June 5th) on our last weekly touchpoint!</strong></span>👋</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>